### ISSUE TITLE
Update meta.yaml dependencies to match CRAN dependencies

### ISSUE THREAD

**Issue by russHyde** [conda-forge/r-diagrammer-feedstock#3]
Hi. I'm going to submit a pull-request to fix the following.
The dependencies for r-diagrammer (for which the current version is version 1.0.0) in meta.yaml are inconsistent with those for DiagrammeR-v1.0.0 at CRAN; so when I installed r-diagrammer in an existing conda env, DiagrammeR threw errors on import.

The CRAN dependencies are:
dplyr (≥ 0.7.4)
downloader (≥ 0.4)
glue (≥ 1.2.0)
htmltools (≥ 0.3.6)
htmlwidgets (≥ 1.0)
igraph (≥ 1.1.2)
influenceR (≥ 0.1.0)
magrittr (≥ 1.5)
purrr (≥ 0.2.4)
RColorBrewer (≥ 1.1-2)
readr (≥ 1.1.1)
rlang (≥ 0.2.0)
rstudioapi (≥ 0.7)
rgexf (≥ 0.15.3)
scales (≥ 0.5.0)
stringr (≥ 1.3.0)
tibble (≥ 1.4.2)
tidyr (≥ 0.8.0)
viridis (≥ 0.5.0)
visNetwork (≥ 2.0.3)

The meta.yaml deps are:
    - r-base
    - r-dplyr >=0.5.0
    - r-downloader >=0.4
    - r-htmltools >=0.3.6
    - r-htmlwidgets >=1.0
    - r-igraph >=1.1.2
    - r-influencer >=0.1.0
    - r-magrittr >=1.5
    - r-purrr >=0.2.3
    - r-rcolorbrewer >=1.1_2
    - r-readr >=1.1.1
    - r-rlang >=0.1.1
    - r-rstudioapi >=0.6
    - r-rgexf >=0.15.3
    - r-scales >=0.5.0
    - r-stringr >=1.2.0
    - r-tibble >=1.3.3
    - r-tidyr >=0.6.3
    - r-viridis >=0.5.0
    - r-visnetwork >=2.0.1

**Comment by dbast** [comment]
Done in https://github.com/conda-forge/r-diagrammer-feedstock/pull/6
